# Generated by Django 5.1.1 on 2024-10-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climateweb', '0002_alter_echochoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='echochoice',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
